### ISSUE TITLE
On Data to Practice With

### ISSUE THREAD

**Issue by hydrosquall** [datasciencemasters/go#100]
Thanks for putting this together! 3 quick thoughts on helping people find cool data to get started with:
- The Guardian link appears to no longer be working: https://github.com/datasciencemasters/go/blob/master/datasets.md
- Consider replacing it with the ["awesome public datasets"](https://github.com/caesar0301/awesome-public-datasets) repository
- Adding descriptions to the nature of each dataset, e.g. in line with what was done in this [blog post](http://www.datasciencecentral.com/profiles/blogs/ten-favorite-open-data-libraries-by-justin-tenuto)? Alternatedly, this could be added to the "curated lists"

Another category could be "dataset newsletters", as Jeremy Singer-Vine's weekly newsletter features new ones every week. http://tinyletter.com/data-is-plural/archive .

**Comment by hydrosquall** [comment]
Edit: perhaps the document could link out to the other data repo this account has, which already links to the "awesome public datasets" account: https://github.com/datasciencemasters/data

**Comment by clarecorthell** [comment]
Thank you for your suggestions! If you would like to make these edits as you suggest, you are welcome to open a pull request with them. If that is new to you, check out Github's educational materials on how to create a PR.

**Comment by elyxir4lyf** [comment]
Segun John, Oni
________________________________
