### ISSUE TITLE
Harvard Videos Dead Now Too

### ISSUE THREAD

**Issue by mdtdev** [datasciencemasters/go#108]
The Harvard videos won't work for me at all--they give error messages on trying to watch. The slides are still ok, but the videos don't work. Are there system specific issues with this? I was only able to test them on OS X.

**Comment by weirwolf** [comment]
I get the same with Linux Mint 18 and Chrome 52.0.2743.116 (64-bit)

**Comment by robert8138** [comment]
@mdtdev @weirwolf Are you guys referring to http://cs109.github.io/2015/?

**Comment by weirwolf** [comment]
@robert8138 No, this: http://cm.dce.harvard.edu/2014/01/14328/publicationListing.shtml

**Comment by robert8138** [comment]
The content should largely be the same, no? (except the few guest speakers)

**Comment by mdtdev** [comment]
I cannot get any of the videos to load, the original link or the link sent by @robert8138 either.

**Comment by SidVader** [comment]
[Data Science](https://www.youtube.com/watch?v=1mUzQZGwgVs&list=PLb4G5axmLqiuneCqlJD2bYFkBwHuOzKus) 
The videos are available on youtube, but it is not an official release by Harvard University. I think they have removed the videos due to some copyrights issue.

**Comment by clarecorthell** [comment]
This is truly unfortunate!

In 2022, the OSDSM was significantly restructured and focuses on up-to-date or still existing resources. If you have suggestions or feedback, please feel free to open an issue or PR to discuss. Thank you for flagging this!
