### ISSUE TITLE
Remove learning python the hardway

### ISSUE THREAD

**Issue by Jan-Ko** [datasciencemasters/go#111]
Hey, since LPTHW warns on using python 3, the python reddit removed it from the sidebar (https://www.reddit.com/r/Python/comments/40s6dm/meta_can_we_take_learn_python_the_hard_way_off/) maybe we should also remove it from the list until a python 3 version is available.

We should also not that the jupyter notebook server will only support python 3 in the future (http://blog.jupyter.org/2016/07/08/ipython-5-0-released/)

**Comment by clarecorthell** [comment]
We'll support 2.7 in the meantime. Transition periods suffer some ambiguity and porting issues, but we'll maintain 2.7 resources until industry has transitioned over wholesale. Thanks for commenting!
