### ISSUE TITLE
Two more graph libraries

### ISSUE THREAD

**Issue by jliebana** [datasciencemasters/go#114]
Hi!
These two links are really recommended libraries for graph processing as you already mentioned NetworkX. We worked with both of them with graphs over 5M nodes without any problem.

Graph tool (fast and efficient Python library):
https://graph-tool.skewed.de/

iGraph (with many algorithms implemented, and available in C, python and R):
http://igraph.org/

Regards

**Comment by clarecorthell** [comment]
Thank you for your suggestion! networkx is included primarily on the merits of its simplicity for beginners. If you'd suggest either of these on that measure to replace it, please respond and share your insights! Will close for now, you can reopen.
