### ISSUE TITLE
Broken link to Statistics course con Coursera - Princeton

### ISSUE THREAD

**Issue by alfredocambera** [datasciencemasters/go#121]
The link to the Statistics course by Princeton on Coursera is broken. The course is not available anymore.

**Comment by clarecorthell** [comment]
Oh, bummer. I've made the fix. Thank you for letting me know! 

Anything we should replace it with?

**Comment by dvanic** [comment]
I don't think the fix has worked - I can still see it online. I don't know, what did the original course cover? There is a series of a statistics course from Stanford, but I'm not sure they it's the same: https://lagunita.stanford.edu/courses/OLI/ProbStat/Open/about
