### ISSUE TITLE
Recommendation and clarification on getting started

### ISSUE THREAD

**Issue by tobiolalusi** [datasciencemasters/go#142]
I have gone through this curriculum and found it very very helpful. I really appreciate your effort of gathering all these for everyone.
Looks like a lot to cover, but I believe I can scale through it all. Everything seems very clear from the middle; mostly after the Maths section. My main issue is on getting started. On the first part (start here), are you to pick one of the 3 options to go on? Or you go through all the courses there and focus on the particular topics provided? Or everything generally?
Same thing applies to the Maths sections. Pick one or two books or go through them all?

A clear description or recommendation on how to go about it could be of better help, so as to focus on the important things and not just beating around the bush.

The computing section is very clear as there is an average of about 2 resources to go through on each aspect of computing. Just the intro seems a little confusing, as each one of them offer almost the same thing.

**Comment by clarecorthell** [comment]
@tobiolalusi -
Thank you for your feedback! I hope you can take a look at the newly structured OSDSM, which provides much more of the guidance you're requesting. Please do take a look and let me know if it's helpful to you. You can reopen this issue if desired. Cheers!
