### ISSUE TITLE
Dead Link in README.md

### ISSUE THREAD

**Issue by kkin1995** [datasciencemasters/go#166]
Hi, there is a dead link in README.md for Differential Equations in Data Science "Python Tutorial".

It takes the user to an online jupyter notebook link with a 404 Error.

**Comment by yk-2310** [comment]
Should we remove it?

**Comment by LukeHaushalter** [comment]
Should be fixed with Pull Request #167

**Comment by clarecorthell** [comment]
Thanks for the catch everyone!
