### ISSUE TITLE
Two lab-heavy data classes on github

### ISSUE THREAD

**Issue by marcua** [datasciencemasters/go#17]
(Full disclosure: I was one of the creators of each of these courses)

This is a class that we taught at MIT called "From ASCII to Answers: Advanced Topics in Data Processing".  The course website is http://db.csail.mit.edu/6.885/, but the entirety of the lectures and 8 labs are available on github: https://github.com/mitdbg/asciiclass/

Another class that Eugene Wu and I taught on Data Literacy: http://dataiap.github.io/dataiap/.  Content is here: https://github.com/dataiap/dataiap.  This class was more introductory, and gives students six three-hour labs to walk them through data cleaning/visualization/statistics/text processing/mapreduce in Python.

If these can be of any help here, let us know!

**Comment by clarecorthell** [comment]
Hi @marcua - curious if revisiting this (now... 9 years later! wow) in the rebuilt OSDSM makes sense. Take a look at the new format, if you like, and let me know! Cheers
