### ISSUE TITLE
Differential Equations in Data Science notebook not found (link throws 404 error)

### ISSUE THREAD

**Issue by sid-sr** [datasciencemasters/go#176]
[This](https://nbviewer.jupyter.org/github/URXtech/techblog/blob/master/continuousTimeMarkovChain/markovChain.ipynb) link for 'Differential Equations in Data Science' under the Math section of the website throws a 404 error, looks like the notebook was deleted from the original repository.

**Comment by clarecorthell** [comment]
Thank you for the catch! This has been corrected.
