### ISSUE TITLE
What happens after the OSDSM?

### ISSUE THREAD

**Issue by clarecorthell** [datasciencemasters/go#70]
I get emails from people thanking me for the OSDSM. Many also ask **what to do next**, or what career they can choose after studying pieces of the curriculum.

Let's open the conversation:
- What do you **want to work on?** (not job title, but the work itself)
- What **projects** helped you learn?
- **What does the OSDSM lack?**

**Comment by clarecorthell** [comment]
Here's a fun list of all the job titles you could possible conceive of:

[The brief multi-tweet enumeration of job titles encompassed by Data Science](https://medium.com/@clarecorthell/the-brief-multi-tweet-enumeration-of-job-titles-encompassed-by-data-science-8d48a988e3a1)

**Comment by edward408** [comment]
Hi Clare!

How do you think someone who currently works full-time can do this type of massive studying part-time in evenings and weekends?

Also, what has been the reception of other employers towards aspiring data scientists who have taken your approach?

**Comment by iblong2iyush** [comment]
I'm a recent CS Engineering Graduate and while apply for my Master's to International Institutions I mentioned OSDSM, fingers crossed as of now!
Awaiting results.

**Comment by schmico** [comment]
Hi Clare - I'm not sure if it's the right place to do it - but I thought that I would raise an issue for facilitating team approaches to capstone projects. 

I think that the OSDSM is great - if you were to compare it against the other 'bootcamps' out there, I think that it's just that team element around the capstone project that is missing.

**Comment by clarecorthell** [comment]
Please, this is a great place to raise the issue! I'd love to hear more
about what you're thinking. There have been a few reddit threads where
learners have sought study groups, perhaps there's opportunity there as
well.

*Clare Corthell*
*Co-Founder, summer.ai <http://summer.ai>** Machine Intelligence Strategy*
*Author, The Open Source Data Science Masters
<http://datasciencemasters.org/>*
*email clarecorthell@gmail.com <clarecorthell@gmail.com>*
*twitter @clarecorthell <http://www.twitter.com/clarecorthell> | linkedin
<http://linkedin.com/in/clarecorthell>*
☏ *650-862-5374*

**Comment by schmico** [comment]
Yeah local study groups could work well, but I think that the strength of OSDSM is that you have a published list of courses that you _should_ aim to complete, but it's not prescriptive in what order you complete it. 

What if we created another folder /capstone projects, much like /transcripts. People embarking on a capstone project would then do the following:
1. Create you're git repository containing a readme.md outlining your proposed capstone project
2. Raise an issue linking back to your capstone project github repo calling for project partners?

OR if you don't have a project in mind we could raise an issue every week / fortnight / month calling for people to comment who are looking for a group to collaborate on capstone project with.

*Side note:*
Encouraging local meetups themed around the OSDSM would allow local groups to cycle speakers in and out relevant to the curriculum + facilitate introductions for capstone projects too.

**Comment by clarecorthell** [comment]
I changed my mind. Here it is:
https://github.com/datasciencemasters/capstone/

This way, requests can be filed (people who aren't actually going to do the
work, business people, curious passerbys) and people can pick them up if
they want to take on a project.

I think the recipe is:
- *Dataset* (must be available somehow, of course)
- *Question* (that is perceived to be possible to answer with the data)

Then people can raise issues on particular capstone listings, which are
each an .md file in the /capstone repo. I like the idea of routinely making
a call for collaborators.

Thanks for raising this issue! I needed a little push to actually invest
ten minutes in a new part of the OSDSM for this. I really appreciate it.

Do you have further thoughts? Looking for a project team yourself?

Clare

*Clare Corthell*
*Co-Founder, summer.ai <http://summer.ai>** Machine Intelligence Strategy*
*Author, The Open Source Data Science Masters
<http://datasciencemasters.org/>*
*email clarecorthell@gmail.com <clarecorthell@gmail.com>*
*twitter @clarecorthell <http://www.twitter.com/clarecorthell> | linkedin
<http://linkedin.com/in/clarecorthell>*
☏ *650-862-5374*

**Comment by schmico** [comment]
This is great. It also allows the OSDSM project to continue to vet peoples work through pull requests etc too. Perhaps suggesting people (as a minimum) document their project, but ideally submit their code too.

I am / will be looking for a team. I do have some background in data sciences, so perhaps not as green as some, which is helpful. When I consider a capstone project, I'm look at it from two angles:
 1. Personal: Is there a world view or hypothesis that you would like to test, and see an opportunity to do so using a data driven approach?
 2. External: another individual or organisation has a hypothesis they need tested

If we just facilitate #2 then that's not all that difficult other then vetting good projects. But may be there are some materials that we could curate around #1 to help people along their capstone journey. I'm thinking just basic reminders of the scientific method to help stay focused.

With respect to #2, I came across [Coursolve](http://www.coursolve.org) today, and have just finished signing up. That seems to be a really interesting approach to introducing real world problems for 'digital interns' to work on. Once I know more I'll share here. I suppose there'd be more resources like this that we could share as part of OSDSM.

**Comment by schmico** [comment]
I just looked at [Coursolve](http://www.coursolve.org) - the idea is great, but it hasn't been taken up. 
But it's worth checking out, you might have ideas against that that I haven't thought of yet.

I'll give some more rigorous thought to the capstone project idea that I had, and then use your system to raise a new project, and see how much attention we can attract from others in the community to join in.

**Comment by schmico** [comment]
I guess the next thing that came to mind is what an 'open source data science PhD' would look like...

**Comment by clarecorthell** [comment]
I've concluded that's equivalent to working for a company for 2+ years. I
mulled it over many a time, but applications are the best place to hone
your deep knowledge.

**Comment by clarecorthell** [comment]
The OSDSM has been significantly restructured, and took this feedback to heart. If you'd like, take a look and give some feedback! This issue can be reopened with that commentary. Cheers!
