### ISSUE TITLE
Facilitating team capstone projects

### ISSUE THREAD

**Issue by schmico** [datasciencemasters/go#81]
Hi Clare and all.

As I mentioned against another issue - I think that we could do a better job in facilitating team capstone projects. We would just need a system for proposing a project / raising a request for joining one. 

Perhaps this could be done through the wiki or via issues?

Any other thoughts?

**Comment by clarecorthell** [comment]
_[pushing the heart of the email thread public]_

Please, this is a great place to raise the issue! I'd love to hear more about what you're thinking. There have been a few reddit threads where learners have sought study groups, perhaps there's opportunity there as well.

**Comment by clarecorthell** [comment]
I like the idea of filing an issue. Happy to abuse issues for the good of all.

**Comment by schmico** [comment]
@clarecorthell it does seem to be abusing Github a bit hey! Reddit threads? 
You mentioned Reddit, r/OpenSourceDataScience: Monthly capstone callout is probably a much better space

**Comment by schmico** [comment]
Moving this issue chat to "what happens after OSDSM" thread. Good progress being made :)
