### ISSUE TITLE
Some of these courses may fit the curriculum

### ISSUE THREAD

**Issue by jaytaylopub** [datasciencemasters/go#88]
@clarecorthell  I wanted to recommend reviewing the online Data Science courses University of Wisconsin does and to add any that my be appropriate! 

http://datasciencedegree.wisconsin.edu/data-science-program/data-science-courses/

**Comment by clarecorthell** [comment]
Have you reviewed them? Why would you recommend them? State your case :)

**Comment by jaytaylopub** [comment]
@clarecorthell I'm actually enrolled in their online program. To be more specific I've found the following programs most useful, so here's some more info on them. There's also a program guide on the UW website that I suggest reviewing for more details. I'll include a link below.

DS 700: Foundations of Data Science
Creating and managing simple databases (SQL Server, Access, R).

DS 710: Programming for Data Science
Data analysis of real-world, numerical, text-based, and social media w/ Python, R, Git, & API's.

DS 730: Big Data: High-Performance Computing
Using Hadoop, Pig, Hive, etc to compare, process large data sets & creating algorithms to process large data sets. 

UW Data Science Program Guide: http://datasciencedegree.wisconsin.edu/wp-content/uploads/UW_DSD_Program_Guide.pdf

Best,
Jay

**Comment by KhumbulaTS** [comment]
@jaytaylopub, I noticed that UW's courses (3 credits per course) come with a hefty price tag in comparison to to the full scope of information as posted by @clarecorthell 

"Tuition for the online Master of Science in Data Science program is a flat fee of $825 per credit ($29,700 total for 36 credits) whether you live in Wisconsin or out of state." - * Taken from [UW Data Science Tuition & Financial Aid](http://datasciencedegree.wisconsin.edu/getting-started/data-science-tuition-financial-aid/)

**Comment by haijingliu** [comment]
Even Online is not affordable

On Friday, February 26, 2016, KhumbulaTS <notifications@github.com> wrote:

> @jaytaylopub <https://github.com/jaytaylopub>, I noticed that UW's
> courses (3 credits per course) come with a hefty price tag in comparison to
> to the full scope of information as posted by @clarecorthell
> <https://github.com/clarecorthell>
>
> "Tuition for the online Master of Science in Data Science program is a
> flat fee of $825 per credit ($29,700 total for 36 credits) whether you live
> in Wisconsin or out of state." - * Taken from UW Data Science Tuition &
> Financial Aid
> <http://datasciencedegree.wisconsin.edu/getting-started/data-science-tuition-financial-aid/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datasciencemasters/go/issues/88#issuecomment-189201353>
> .
>


-- 
Haijing Liu
Visual / Interaction Designer
MFA'14 design and technology Parsons
--
http://haijing.info/portfolio
--

tel: +1 9176187879
skype: charl.leo
twitter: charl28th

**Comment by clarecorthell** [comment]
These courses are not online and free. Closing.
