### ISSUE TITLE
Are you still maintaining this repo?

### ISSUE THREAD

**Issue by fhlgood** [datasciencemasters/go#94]
This is a wonderful place to look for resources about data science education.
 I really hope that the author is still active because some links are broken in README. There are quite a number of pull requests that has not been well-addressed, and I wonder if I should contribute to this repo.

**Comment by Dawny33** [comment]
Clare just updated the repo 14 hours ago. So, looks like it is indeed actively maintained. 

So, pl go ahead and send in your contributions :)

**Comment by fhlgood** [comment]
Good to know that!

**Comment by clarecorthell** [comment]
Thanks for contributing pull requests when you see broken links, I appreciate it!
