### ISSUE TITLE
Feature Request: Contributing.md ?

### ISSUE THREAD

**Issue by mikezawitkowski** [datasciencemasters/go#98]
I like that you note at the bottom of this that others should contribute. Perhaps we can expand upon that a little further, and add a Contributing.md file with instructions? 

I'm curious about whether contributions are preferred in a certain format, say forking the repo, then making a change, and submitting it as a pull request? Or is it more open than that?

More importantly, what _kind_ of contributions are welcome or needed? Are there areas that have been identified as needing further development? I don't necessarily agree with all of the items here, and I have come across my own books and courses that I think are better suited, but is this purely a big list that we add to, and not replace or substitute existing items? 

Thanks for putting this repo together, it is very valuable and I refer to it often :)

**Comment by pedstrom** [comment]
+1 to a "How to Contribute" section.

One of the things I am finding lacking is some kind of estimate for each task/course/book on the list. For example the Statistics I [Princeton / Coursera](https://www.coursera.org/course/stats1) class, is going to be a 12 week class - when offered next - and they suggest you will need 5-8 hours/week to complete the course. I'd love to look through all of classes/books/etc and surface some of that information directly into the list. Would this be a welcome pull request? 

Similar, but slightly different, It might be helpful to spell out "How to take this Masters" as well. Should my goal be to be able to say "I completed _The_ Open Source Data Science Masters" or should my goal be to say "I created and completed _my own_ Open Source Data Science Masters"? I think I prefer the former as attaching to a group lends credibility, even if that group is an open source community-based curriculum. This leads me to ask about the role of the /transcripts folder - is that something open to any and all, or would I manage my transcript in my own fork of this repo?

**Comment by clarecorthell** [comment]
Much of the qualitative feedback offered in the past has been taken into account in the rebuilt OSDSM, pushed late last year. Please take a look and relay any updated feedback! Thank you for your thoughtful suggestions about how to engage folks here.
