### ISSUE TITLE
New link to Hardtke quote source

### ISSUE THREAD

**Issue by mikezawitkowski** [datasciencemasters/go#99]
On the home page of http://datasciencemasters.org/ there is a quote followed by a citation

> David Hardtke How To Hire A Data Scientist 13 Nov 2012

And that citation has a bitly link embedded in it...

http://bit.ly/howtohireadatascientist

...and that bitly link resolves to...

http://blog.bright.com/2012/11/13/how-to-hire-a-data-scientist/

..which is broken.

(FWIW I see that this link was removed entirely from the [README.md](https://github.com/datasciencemasters/go/blob/master/README.md) page)

The link is not lost, however, and the new link to that same article is here:

https://brightemployers.wordpress.com/2012/11/13/how-to-hire-a-data-scientist/

**I'd recommend updating the README.md page, and also the datasciencemasters.org page so that the quote points to the new link**, but the less attractive alternative would be to remove the broken link from datasciencemasters.org

**Comment by clarecorthell** [comment]
Thanks for the catch! Due to restructuring, this resource has been eliminated or moved.
